### ISSUE TITLE
Background Color

### ISSUE THREAD

**Issue by Krazytrain** [Dyzean/Simplify#4]
The background color dont change at all on the friends list. 

This is the code i used to fix it.

/*Freind List Background*/
.peopleColumn-1wMU14 {
    background-color: #181d33
}

![image](https://user-images.githubusercontent.com/54170019/148879654-bf7d47ee-06f3-4857-a0b8-f0bd2577e6d7.png)

**Comment by Dinoslav** [comment]
Yeah more things are broken since yesterday.

Home menu
![image](https://user-images.githubusercontent.com/68663248/148995482-4dd5d5d3-2860-421a-84f2-d414790b9693.png)

Emote menu
![image](https://user-images.githubusercontent.com/68663248/148995612-794ae032-6f69-4216-b23d-49da6293b210.png)

Typing bar not outlined 
![image](https://user-images.githubusercontent.com/68663248/148995779-1835dcb8-50d5-43f7-8559-e3238e3f3d47.png)

**Comment by Krazytrain** [comment]
> Yeah more things are broken since yesterday.
> 
> Home menu ![image](https://user-images.githubusercontent.com/68663248/148995482-4dd5d5d3-2860-421a-84f2-d414790b9693.png)
> 
> Emote menu ![image](https://user-images.githubusercontent.com/68663248/148995612-794ae032-6f69-4216-b23d-49da6293b210.png)
> 
> Typing bar not outlined ![image](https://user-images.githubusercontent.com/68663248/148995779-1835dcb8-50d5-43f7-8559-e3238e3f3d47.png)

A quick fix but there is alot broken right now =/


/Freind List Background/
.peopleColumn-1wMU14 {
background-color: #181d33
}
/*Emoji Picker*/
.scroller-18M1mG {
    padding-bottom: 8px;
    background-color: #181d33;
}

**Comment by Dyzean** [comment]
This is known, i will fix it next week because im still on vacation right now. im really sorry.

**Comment by Dinoslav** [comment]
> This is known, i will fix it next week because im still on vacation right now. im really sorry.

Don't stress about it. Enjoy you vacation!

**Comment by ashtrath** [comment]
Fixed in latest commit 👍🏼

**Comment by Dinoslav** [comment]
Thanks
